### ISSUE TITLE
I have an error of logging

### ISSUE THREAD

**Issue by Paullux** [powerjungle/fbridge-asyncio#1]
```python
Paullux@dvkbuntu:~/fbridge-asyncio$ python3 fbridge-asyncio.py
INFO:root:Logging started
INFO:root:Found empty fb_dtsg, the session was probably invalid.
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcded98c0d0>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fcded9a57c0>, 3775571.95251181)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fcded98c100>
ERROR:root:Session could not be loaded, login instead!
Password:
Traceback (most recent call last):
  File "fbridge-asyncio.py", line 325, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "fbridge-asyncio.py", line 304, in main
    session = await fbchat.Session.login(getpass.getuser(), getpass.getpass())
  File "/home/Paullux/.local/lib/python3.8/site-packages/fbchat/_session.py", line 416, in login
    raise _exception.NotLoggedIn(error)
fbchat.NotLoggedIn: Le mot de passe entré est incorrect. Vous l’avez oublié ?
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcded98c130>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fcded9b9e20>, 3775579.56332407)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fcded98c0d0>
```

**Comment by powerjungle** [comment]
Well for now I suggest you try logging in with cookies: https://github.com/tulir/fbchat-asyncio#examples

**Comment by powerjungle** [comment]
I'll close this, since no response is given for a long time.

**Comment by Thanatoslayer6** [comment]
I got this same issue although i solved it shortly because, the problem is that my "xs" variable changed..... probably caused by changing some settings in my account.... like removing a phone number?? not sure....
